name: Create Work Item in Azure DevOps from Issue

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:
        github_token: 'temp'
        ado_token: 'temp'
        ado_organization: 'https://dev.azure.com/privatepreview'
        ado_project: 'my project'
